### ISSUE TITLE
JavaScript variations and motor control

### ISSUE THREAD

**Issue by embeddednodejs** [ThomasCLee/funnyvale#1]
Hi Thomas,

just wanted to point to this example where I made a JavaScript version from your first example:

https://github.com/embeddednodejs/ch_9_making_robots_with_nodejs/tree/master/vehicle

The Fabric shield is really nice.
I was a bit wondering if you have thought about variations for the motor control, e.g. similar to the motor controls of the Arduino shield: http://johnny-five.io/examples/motor-directional/  (throttle/brake) or PWM control of the motors?

BR,

Patrick

**Comment by ThomasCLee** [comment]
Thank you for sharing.
I will look at the example you sent.

I uploaded an example showing how to control motor speed using PWM with fabric shield. Please check it out:

https://github.com/ThomasCLee/funnyvale/tree/master/hackabot_nano/Tutorial6_control_motor_speed_with_pwm

**Comment by embeddednodejs** [comment]
Thanks. That was the same approach that I tried yesterday with PWM and JavaScript. Interestingly, today the wheels move only very slowly (based on my JavaScript version).
