### ISSUE TITLE
Errors for WiThumb Example 3

### ISSUE THREAD

**Issue by kd8bxp** [ThomasCLee/funnyvale#2]
Maybe related to I2Cdev library or something in the library, or I have the wrong library - I think it's a library issue, but it's a bit beyond me.

`
Arduino: 1.6.9 (Linux), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, 115200, 4M (3M SPIFFS)"

WARNING: Spurious .github folder in 'Adafruit PCD8544 Nokia 5110 LCD library' library
WARNING: Spurious .github folder in 'Adafruit ILI9341' library
WARNING: Spurious .github folder in 'Adafruit MLX90614 Library' library
libraries/MPU6050/I2Cdev.cpp.o: In function `I2Cdev::I2Cdev()':
Multiple libraries were found for "I2Cdev.h"
 Used: /home/lfmiller/Arduino/libraries/I2Cdev
 Not used: /home/lfmiller/Arduino/libraries/MPU6050
/home/lfmiller/Arduino/libraries/MPU6050/I2Cdev.cpp:53: multiple definition of `I2Cdev::I2Cdev()'
libraries/I2Cdev/I2Cdev.cpp.o:/home/lfmiller/Arduino/libraries/I2Cdev/I2Cdev.cpp:92: first defined here
libraries/MPU6050/I2Cdev.cpp.o: In function `I2Cdev::I2Cdev()':
/home/lfmiller/Arduino/libraries/MPU6050/I2Cdev.cpp:53: multiple definition of `I2Cdev::I2Cdev()'
libraries/I2Cdev/I2Cdev.cpp.o:/home/lfmiller/Arduino/libraries/I2Cdev/I2Cdev.cpp:92: first defined here
libraries/MPU6050/I2Cdev.cpp.o: In function `I2Cdev::writeWord(unsigned char, unsigned char, unsigned short)':
/home/lfmiller/Arduino/libraries/MPU6050/I2Cdev.cpp:399: multiple definition of `I2Cdev::writeBytes(unsigned char, unsigned char, unsigned char, unsigned char*)'
libraries/I2Cdev/I2Cdev.cpp.o:/home/lfmiller/Arduino/libraries/I2Cdev/I2Cdev.cpp:583: first defined here
libraries/MPU6050/I2Cdev.cpp.o: In function `I2Cdev::writeBitsW(unsigned char, unsigned char, unsigned char, unsigned char, unsigned short)':
/home/lfmiller/Arduino/libraries/MPU6050/I2Cdev.cpp:378: multiple definition of `I2Cdev::writeByte(unsigned char, unsigned char, unsigned char)'
libraries/I2Cdev/I2Cdev.cpp.o:/home/lfmiller/Arduino/libraries/I2Cdev/I2Cdev.cpp:562: first defined here
libraries/MPU6050/I2Cdev.cpp.o: In function `I2Cdev::readWords(unsigned char, unsigned char, unsigned char, unsigned short*, unsigned short)':
/home/lfmiller/Arduino/libraries/MPU6050/I2Cdev.cpp:446: multiple definition of `I2Cdev::writeWords(unsigned char, unsigned char, unsigned char, unsigned short*)'
libraries/I2Cdev/I2Cdev.cpp.o:/home/lfmiller/Arduino/libraries/I2Cdev/I2Cdev.cpp:638: first defined here
libraries/MPU6050/I2Cdev.cpp.o: In function `I2Cdev::writeWord(unsigned char, unsigned char, unsigned short)':
/home/lfmiller/Arduino/libraries/MPU6050/I2Cdev.cpp:388: multiple definition of `I2Cdev::writeWord(unsigned char, unsigned char, unsigned short)'
libraries/I2Cdev/I2Cdev.cpp.o:/home/lfmiller/Arduino/libraries/I2Cdev/I2Cdev.cpp:572: first defined here
libraries/MPU6050/I2Cdev.cpp.o: In function `I2Cdev::readBytes(unsigned char, unsigned char, unsigned char, unsigned char*, unsigned short)':
/home/lfmiller/Arduino/libraries/MPU6050/I2Cdev.cpp:167: multiple definition of `I2Cdev::readBytes(unsigned char, unsigned char, unsigned char, unsigned char*, unsigned short)'
libraries/I2Cdev/I2Cdev.cpp.o:/home/lfmiller/Arduino/libraries/I2Cdev/I2Cdev.cpp:206: first defined here
libraries/MPU6050/I2Cdev.cpp.o: In function `I2Cdev::readByte(unsigned char, unsigned char, unsigned char*, unsigned short)':
/home/lfmiller/Arduino/libraries/MPU6050/I2Cdev.cpp:144: multiple definition of `I2Cdev::readByte(unsigned char, unsigned char, unsigned char*, unsigned short)'
libraries/I2Cdev/I2Cdev.cpp.o:/home/lfmiller/Arduino/libraries/I2Cdev/I2Cdev.cpp:183: first defined here
libraries/MPU6050/I2Cdev.cpp.o: In function `I2Cdev::readBit(unsigned char, unsigned char, unsigned char, unsigned char*, unsigned short)':
/home/lfmiller/Arduino/libraries/MPU6050/I2Cdev.cpp:64: multiple definition of `I2Cdev::readBit(unsigned char, unsigned char, unsigned char, unsigned char*, unsigned short)'
libraries/I2Cdev/I2Cdev.cpp.o:/home/lfmiller/Arduino/libraries/I2Cdev/I2Cdev.cpp:103: first defined here
libraries/MPU6050/I2Cdev.cpp.o: In function `I2Cdev::readBits(unsigned char, unsigned char, unsigned char, unsigned char, unsigned char*, unsigned short)':
/home/lfmiller/Arduino/libraries/MPU6050/I2Cdev.cpp:95: multiple definition of `I2Cdev::readBits(unsigned char, unsigned char, unsigned char, unsigned char, unsigned char*, unsigned short)'
libraries/I2Cdev/I2Cdev.cpp.o:/home/lfmiller/Arduino/libraries/I2Cdev/I2Cdev.cpp:134: first defined here
libraries/MPU6050/I2Cdev.cpp.o:(.data._ZN6I2Cdev11readTimeoutE+0x0): multiple definition of `I2Cdev::readTimeout'
libraries/I2Cdev/I2Cdev.cpp.o:(.data._ZN6I2Cdev11readTimeoutE+0x0): first defined here
libraries/MPU6050/I2Cdev.cpp.o: In function `I2Cdev::writeBit(unsigned char, unsigned char, unsigned char, unsigned char)':
/home/lfmiller/Arduino/libraries/MPU6050/I2Cdev.cpp:293: multiple definition of `I2Cdev::writeBit(unsigned char, unsigned char, unsigned char, unsigned char)'
libraries/I2Cdev/I2Cdev.cpp.o:/home/lfmiller/Arduino/libraries/I2Cdev/I2Cdev.cpp:477: first defined here
libraries/MPU6050/I2Cdev.cpp.o: In function `I2Cdev::writeBits(unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)':
/home/lfmiller/Arduino/libraries/MPU6050/I2Cdev.cpp:322: multiple definition of `I2Cdev::writeBits(unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)'
libraries/I2Cdev/I2Cdev.cpp.o:/home/lfmiller/Arduino/libraries/I2Cdev/I2Cdev.cpp:506: first defined here
libraries/MPU6050/I2Cdev.cpp.o: In function `I2Cdev::readWords(unsigned char, unsigned char, unsigned char, unsigned short*, unsigned short)':
/home/lfmiller/Arduino/libraries/MPU6050/I2Cdev.cpp:224: multiple definition of `I2Cdev::readWords(unsigned char, unsigned char, unsigned char, unsigned short*, unsigned short)'
libraries/I2Cdev/I2Cdev.cpp.o:/home/lfmiller/Arduino/libraries/I2Cdev/I2Cdev.cpp:326: first defined here
libraries/MPU6050/I2Cdev.cpp.o: In function `I2Cdev::readWord(unsigned char, unsigned char, unsigned short*, unsigned short)':
/home/lfmiller/Arduino/libraries/MPU6050/I2Cdev.cpp:155: multiple definition of `I2Cdev::readWord(unsigned char, unsigned char, unsigned short*, unsigned short)'
libraries/I2Cdev/I2Cdev.cpp.o:/home/lfmiller/Arduino/libraries/I2Cdev/I2Cdev.cpp:194: first defined here
libraries/MPU6050/I2Cdev.cpp.o: In function `I2Cdev::readBitW(unsigned char, unsigned char, unsigned char, unsigned short*, unsigned short)':
/home/lfmiller/Arduino/libraries/MPU6050/I2Cdev.cpp:79: multiple definition of `I2Cdev::readBitW(unsigned char, unsigned char, unsigned char, unsigned short*, unsigned short)'
libraries/I2Cdev/I2Cdev.cpp.o:/home/lfmiller/Arduino/libraries/I2Cdev/I2Cdev.cpp:118: first defined here
libraries/MPU6050/I2Cdev.cpp.o: In function `I2Cdev::readBitsW(unsigned char, unsigned char, unsigned char, unsigned char, unsigned short*, unsigned short)':
/home/lfmiller/Arduino/libraries/MPU6050/I2Cdev.cpp:120: multiple definition of `I2Cdev::readBitsW(unsigned char, unsigned char, unsigned char, unsigned char, unsigned short*, unsigned short)'
libraries/I2Cdev/I2Cdev.cpp.o:/home/lfmiller/Arduino/libraries/I2Cdev/I2Cdev.cpp:159: first defined here
libraries/MPU6050/I2Cdev.cpp.o: In function `I2Cdev::writeBitW(unsigned char, unsigned char, unsigned char, unsigned short)':
/home/lfmiller/Arduino/libraries/MPU6050/I2Cdev.cpp:307: multiple definition of `I2Cdev::writeBitW(unsigned char, unsigned char, unsigned char, unsigned short)'
libraries/I2Cdev/I2Cdev.cpp.o:/home/lfmiller/Arduino/libraries/I2Cdev/I2Cdev.cpp:491: first defined here
libraries/MPU6050/I2Cdev.cpp.o: In function `I2Cdev::writeBitsW(unsigned char, unsigned char, unsigned char, unsigned char, unsigned short)':
/home/lfmiller/Arduino/libraries/MPU6050/I2Cdev.cpp:351: multiple definition of `I2Cdev::writeBitsW(unsigned char, unsigned char, unsigned char, unsigned char, unsigned short)'
libraries/I2Cdev/I2Cdev.cpp.o:/home/lfmiller/Arduino/libraries/I2Cdev/I2Cdev.cpp:535: first defined here
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
`

Any idea where to start or what to do?

**Comment by kd8bxp** [comment]
never mind - sorry, I am a ID10T...  There is a I2Cdev also in the MPU6050 library - MPU6050 wants that one, and the compiler was using a different version....it's working...never mind....

**Comment by ThomasCLee** [comment]
It's great to hear that it is working.
