### ISSUE TITLE
Documented WiThumb sensor access details?

### ISSUE THREAD

**Issue by petri** [ThomasCLee/funnyvale#3]
I am trying to read WiThumb sensor using MicroPython. I managed to install MicroPython and make networking work. However I am having trouble with the sensors.

For example, I was able to figure out from the provided Arduino C code, and withumb schematics, that the temperature sensor is accessible via I2C, at address 0x1F. GIven I did not succeed yet reading the temperature, I guess I am missing something; perhaps initializing the sensor is mandatory, and I am not sure of the correct registers to use when reading/writing over I2C... not being a C programmer by trade, or an electronics engineer, this is really burdensome.

It would be good to have some written, programming language-independent specs on how the sensors are read from and what kind of steps are required.

**Comment by ThomasCLee** [comment]
Thank you for the suggestion. The ultimate language-independent spec is the data sheet from the companies that produce the sensors. 

Regarding help on reading from the sensors through micro-python, you may check out this thread : 

https://forum.micropython.org/viewtopic.php?t=1361

**Comment by petri** [comment]
Thanks, I had found that, too. It seems to me that the Python implementations seem to do a I2C write before reading, for example here:

https://github.com/kfricke/micropython-mcp9808/blob/master/mcp9808.py

Is that what should be done with WiThumb? I can see no other reason for the writes...?

I also added another thread specifically on the WiThumb there:

http://forum.micropython.org/viewtopic.php?f=12&t=2760

On that thread, @deshipu suggested the following:

> I wonder, perhaps the C implementation of the I2C master enables the internal pullups on the pins, and thus manages to communicate without external pullup resistors?

Is that correct on the WiThumb?

**Comment by ThomasCLee** [comment]
Perhaps you could try to enable the internal pull up for SCL and SDA in the beginning. This document shows how to do so with micropython

https://docs.micropython.org/en/latest/esp8266/esp8266/quickref.html

**Comment by ThomasCLee** [comment]
I inserted a couple of weak pull-up resistors to the SCL and SDA pins and ran the following code,
it returns the temperature. Without the resistors, it returns 0.0. It seems that micropython doesn't really enable the internal pullup of pin4 and 5. Perhaps, it is a bug in micropython.


from machine import Pin, I2C

i2c = I2C(scl=Pin(5, Pin.PULL_UP), sda=Pin(4, Pin.PULL_UP), freq=100000)

R_A_TEMP = const(5)

addr=0x1F
raw = i2c.readfrom_mem(addr, R_A_TEMP, 2)
u = (raw[0] & 0x0f) << 4
l = raw[1] / 16
if raw[0] & 0x10 == 0x10:
    temp = 256 - (u + l)
else:
    temp = u + l

print(temp)

**Comment by ThomasCLee** [comment]
This is what I got when doing i2c.scan() with added weak pull-up resistors:

![image](https://cloud.githubusercontent.com/assets/10004907/21308681/e066b476-c58f-11e6-8890-da27317e2658.png)

**Comment by deshipu** [comment]
It's not a bug. The internal pull-up resistors shouldn't be used for I2C communication. Instead external pull-ups should be added, with values adjusted for the particular needs -- depending on the devices connected, desired speed of transmission, length of the lines, voltage, etc. This is a problem with the hardware design.

Using the internal pull-ups can actually lead to problems and even damaged parts if the slave device(s) use different voltage than the master (because the internal pull-ups will be connected to the master's power, not the slave's). They are usually too weak for a reasonable transmission speed anyways, and if enabled, they will interact with the external pull-ups, making it difficult to calculate proper values for them.

**Comment by ThomasCLee** [comment]
I tested it on WiThumb with the following code and it works.

from machine import Pin, I2C

i2c = I2C(scl=Pin(5), sda=Pin(4), freq=100000)

Pin(4).init(Pin.IN,Pin.PULL_UP)
Pin(5).init(Pin.IN,Pin.PULL_UP)

R_A_TEMP = const(5)

addr=0x1F
raw = i2c.readfrom_mem(addr, R_A_TEMP, 2)
u = (raw[0] & 0x0f) << 4
l = raw[1] / 16
if raw[0] & 0x10 == 0x10:
    temp = 256 - (u + l)
else:
    temp = u + l

print(temp)

**Comment by petri** [comment]
Thanks @ThomasCLee & @deshipu, I just managed to make it work, too! :)

    >>> i2c = I2C(scl=Pin(5, Pin.IN, Pin.PULL_UP), sda=Pin(4, Pin.IN, Pin.PULL_UP), freq=10000)
    >>> i2c.scan()
    [31, 104]

It does not seem to me that it matters whether Pin.IN or Pin.OUT is used.

**Comment by petri** [comment]
@deshipu thanks for pointing out potential issues with using internal pull-ups for I2C. If I understood you correctly, then anyone who might want to hook additional I2C-connected sensors to the WiThumb,  should stop using the internal pull-ups, adding and using external ones instead.

**Comment by petri** [comment]
I will write another blog entry to document this (checking temperature on WiThumb using MicroPython) for everyone to use. Thanks again guys! If there's anything more you want to add or point out, just let me know.

**Comment by deshipu** [comment]
@petri that sounds like one possible solution.

**Comment by petri** [comment]
Something I bumped into: “In general, in a system where one device is at a higher voltage than another, it may be possible to connect the two devices via I2C without any level shifting circuitry in between them. The trick is to connect the pull-up resistors to the lower of the two voltages.” (from SparkFun I2C tutorial)

**Comment by ThomasCLee** [comment]
@petri, you don't need to worry about external pull up resistor if you use the onboard sensors. They all work at the same voltage, which is 3.3v.

**Comment by petri** [comment]
Thanks @ThomasCLee. I figured that you must have made sure the internal pull-up resistor voltage and resistance are ok (and sufficient with the two on-board sensors) when doing the WiThumb hw design, but good to hear.

**Comment by petri** [comment]
Dug up the old withumb & flashed it with current Micropython. Works nice, still. Looks like I'd forgotten to link those posts, so here goes: https://koodaamo.wordpress.com/tag/withumb/
